apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-luvv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0034-tenant/tkrw-pr712-0075-0034-app/devfile-sample-luvv@sha256:d0690de2796b898f59403f5e6fc94e9bf9c3a41e57d85dab3353966bef3eae5b
        name: my-nodejs
        resources: {}
status: {}
